name: Deploy to Server

on:
  push:
    branches:
      - main  # 将 'main' 替换为你的默认分支名称（例如 'master'）

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: 检出代码
        uses: actions/checkout@v2

      # 设置 Node.js 环境
      - name: 设置 Node.js 环境
        uses: actions/setup-node@v2
        with:
          node-version: 16

      # 安装依赖项
      - name: 安装依赖项
        run: npm ci

      # 构建项目
      - name: 安装依赖项Build
        run: npm run build

      # 部署到服务器
      - name: Deploy to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: "./"
          target: "../usr/share/nginx/html"
